version: '3.8'

services:
  resume-generator:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
    command: bash /app/scripts/run_server.sh